const mongoose = require('mongoose');

// SynUnion — the cached "union" artifact (UNION.md).
// Replaces the M3 "Ask the Group" Q&A: one document PER COMMUNITY (not per
// user — this is a shared, whole-corpus statement everyone in the community
// sees the same cached copy of), holding a `brief` (2-4 sentences, default)
// and a `full` (structured read) sub-artifact, each independently cached and
// independently regenerated by its own Synthesize/Expand button press.
//
// STALENESS (UNION.md §9): `corpusVersion` is bumped by
// utils/synUnion.js#markStale() every time the published corpus
// changes (utils/synIndexHooks.js fires it alongside the embedding-index
// refresh). Each cached artifact stamps the corpusVersion it was generated
// AT (`atCorpusVersion`); it is stale when that no longer matches the current
// `corpusVersion`. Nothing regenerates automatically — staleness only ever
// surfaces as a badge; a member has to press Synthesize/Expand again.
//
// Citations mirror SynThread's citationSchema (kind/node/reply +
// ownerHandle + anchorUrl) — assembled server-side from the retrieval set,
// never parsed from model output (utils/synUnion.js#assembleCitations).
const citationSchema = new mongoose.Schema({
  kind:        { type: String, enum: ['node', 'reply'] },
  nodeId:      { type: String },
  replyId:     { type: String, default: null },
  ownerHandle: { type: String },
  anchorUrl:   { type: String },
}, { _id: false, id: false });

const artifactSchema = new mongoose.Schema({
  text:           { type: String, default: '' },
  citations:      { type: [citationSchema], default: [] },
  generatedAt:    { type: Date, default: null },
  model:          { type: String, default: '' },
  // The corpusVersion in effect when this artifact was generated — compared
  // against the live `corpusVersion` to decide the stale badge.
  atCorpusVersion: { type: Number, default: 0 },
}, { _id: false, id: false });

const synUnionSchema = new mongoose.Schema({
  id: {
    type: String,
    required: true,
    unique: true,
    index: true,
    default: function () {
      return require('crypto').randomUUID().substring(0, 8);
    },
  },

  instanceId: { type: String, required: true, unique: true, index: true }, // community — one doc per community

  corpusVersion: { type: Number, default: 0 },

  brief: { type: artifactSchema, default: undefined },
  full:  { type: artifactSchema, default: undefined },
}, {
  timestamps: true,
  id: false,
});

module.exports = mongoose.model('SynUnion', synUnionSchema);
